# config/packages/vich_uploader.yaml

vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    produit:
      uri_prefix: /uploads/produits
      upload_destination: '%kernel.project_dir%/public/uploads/produits'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true

    article:
      uri_prefix: /uploads/article
      upload_destination: '%kernel.project_dir%/public/uploads/article'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true

