controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

resend_verif:
    path: /verify/email
    controller: App\Controller\VerificationController::app_verify_email